---
booktitle: Proceedings of 2025 2nd International Conference on Machine Learning and
  Intelligent Computing
shortname: MLIC
volume: '278'
year: '2025'
start: &1 2025-04-25
end: 2025-04-27
published: 2025-10-27
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: MLIC-2025
month: 0
cycles: false
bibtex_editor: Zeng, Nianyin and Pachori, Ram Bilas and Wang, Dongshu
editor:
- given: Nianyin
  family: Zeng
- given: Ram Bilas
  family: Pachori
- given: Dongshu
  family: Wang
title: Proceedings of Machine Learning Research
description: |
  Proceedings of 2025 2nd International Conference on Machine Learning and Intelligent Computing
    Held in Zhengzhou, China on 25-27 April 2025

  Published as Volume 278 by the Proceedings of Machine Learning Research on 27 October 2025.

  Volume Edited by:
    Nianyin Zeng
    Ram Bilas Pachori
    Dongshu Wang

  Series Editors:
    Neil D. Lawrence
date_str: 25--27 Apr
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v278"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v278
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v278
email: ''
conference:
  name: International Conference on Machine Learning and Intelligent Computing
  url: https://www.icmlic.org
  location: Zhengzhou, China
  dates:
  - *1
  - 2025-04-26
  - 2025-04-27
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: mlic25_cleaned_clean.bib
# Site settings
# Original source:  mlic25_cleaned_clean.bib
